### ISSUE TITLE
Header image setting

### ISSUE THREAD

**Issue by ldevore8** [t-hamano/enable-responsive-image#35]
I see no way to make Header images responsive because the only access to them is via page customization settings. Aside from adding Custom CSS, is there another solution? Thank you. Here is a snapshot.
![responsive header](https://github.com/user-attachments/assets/78570515-cfa0-4734-8c4a-77b5a676c292)

**Comment by t-hamano** [comment]
Thanks for the report.

This plugin extends the Image Block, not the Customizer. At the moment, I have no plans to add Customizer extensions to this plugin, so I would like to close it.
